version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /KubeArmor
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /deployments
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /deployments/podman
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /examples/multiubuntu/build
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /pkg/KubeArmorController
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /pkg/KubeArmorController
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /pkg/KubeArmorOperator
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /pkg/KubeArmorOperator
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /protobuf
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /tests
    schedule:
      interval: daily
