name: ci-test-helm-charts

on:
  push:
    branches: [main]
    paths:
      - "deployments/helm/**"
      - ".github/workflows/ci-test-helm-charts.yml"
  pull_request:
    branches: [main]
    paths:
      - "deployments/helm/**"
      - ".github/workflows/ci-test-helm-charts.yml"

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint:
    name: Helm Chart Tests / ubuntu 22.04
    runs-on: "ubuntu-22.04"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: true

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: 'KubeArmor/go.mod'

      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: helm lint
        run: |
          helm lint ./deployments/helm/KubeArmor
          helm lint ./deployments/helm/KubeArmorOperator

      - name: Validate helm environment template values
        run: |
          ./.github/workflows/helm-validate-values.sh
